import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

/**
 * Client-side clinical PDF document generation using jsPDF + html2canvas.
 * Clones the content element and renders with a clean light clinical theme.
 * 
 * @param {string} title Document title
 * @param {string} contentElementId DOM ID of the content container
 */
export async function generatePDF(title, contentElementId = 'iris-artifact-content') {
  const sourceElement = document.getElementById(contentElementId);
  if (!sourceElement) {
    console.error(`[generatePDF] Element #${contentElementId} not found.`);
    return;
  }

  const safeTitle = (title || 'Iris_Medical_Report').replace(/[^a-zA-Z0-9_\-]/g, '_');
  const now = new Date();
  const dateString = now.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  }) + ' · ' + now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  // Create an offscreen clone with clinical light-mode styling
  const printContainer = document.createElement('div');
  printContainer.style.position = 'fixed';
  printContainer.style.left = '-9999px';
  printContainer.style.top = '0';
  printContainer.style.width = '794px'; // Standard A4 width in 96 DPI pixels
  printContainer.style.padding = '48px 40px';
  printContainer.style.backgroundColor = '#FFFFFF';
  printContainer.style.color = '#1A1A1A';
  printContainer.style.fontFamily = 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
  printContainer.style.lineHeight = '1.7';
  printContainer.style.boxSizing = 'border-box';
  printContainer.className = 'iris-pdf-print-root';

  // Professional clinical document header
  const headerDiv = document.createElement('div');
  headerDiv.style.display = 'flex';
  headerDiv.style.alignItems = 'center';
  headerDiv.style.justifyContent = 'space-between';
  headerDiv.style.borderBottom = '2px solid #0B1416';
  headerDiv.style.paddingBottom = '16px';
  headerDiv.style.marginBottom = '28px';

  headerDiv.innerHTML = `
    <div style="display: flex; align-items: center; gap: 8px;">
      <span style="font-family: 'Lora', Georgia, serif; font-weight: 700; font-size: 20px; color: #0B1416; letter-spacing: -0.5px;">Iris</span>
      <span style="font-size: 10px; font-weight: 600; text-transform: uppercase; padding: 2px 6px; border-radius: 4px; background: #9FE2EE; color: #0B1416;">Health Clinical</span>
    </div>
    <div style="font-family: 'Lora', Georgia, serif; font-size: 14px; font-weight: 600; color: #0B1416; text-align: center; max-width: 320px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
      ${title || 'Medical Consultation Report'}
    </div>
    <div style="font-size: 11px; color: #64748B; font-family: monospace;">
      Generated by Iris · ${dateString}
    </div>
  `;
  printContainer.appendChild(headerDiv);

  // Clone artifact content
  const contentClone = sourceElement.cloneNode(true);
  contentClone.removeAttribute('id');

  // Inline light-mode styles on cloned nodes
  const applyLightStyles = (el) => {
    // Headings: Lora serif, dark color
    const headings = el.querySelectorAll('h1, h2, h3, h4, h5, h6');
    headings.forEach((h) => {
      h.style.fontFamily = "'Lora', Georgia, serif";
      h.style.color = '#0B1416';
      h.style.marginTop = '24px';
      h.style.marginBottom = '12px';
      h.style.fontWeight = '700';
    });

    // Paragraphs & lists
    const texts = el.querySelectorAll('p, li, span');
    texts.forEach((p) => {
      p.style.color = '#262626';
      p.style.lineHeight = '1.7';
    });

    // Strong text
    const strongs = el.querySelectorAll('strong, b');
    strongs.forEach((s) => {
      s.style.color = '#0B1416';
      s.style.fontWeight = '700';
    });

    // Clinical tables
    const tables = el.querySelectorAll('table');
    tables.forEach((table) => {
      table.style.width = '100%';
      table.style.borderCollapse = 'collapse';
      table.style.margin = '20px 0';
      table.style.fontSize = '13px';
      table.style.border = '1px solid #CBD5E1';
      table.style.borderRadius = '8px';
      table.style.overflow = 'hidden';
    });

    const ths = el.querySelectorAll('th');
    ths.forEach((th) => {
      th.style.backgroundColor = '#9FE2EE';
      th.style.color = '#0B1416';
      th.style.fontWeight = '700';
      th.style.textAlign = 'left';
      th.style.padding = '10px 12px';
      th.style.border = '1px solid #94A3B8';
    });

    const trs = el.querySelectorAll('tbody tr');
    trs.forEach((tr, i) => {
      tr.style.backgroundColor = i % 2 === 0 ? '#F8FAFC' : '#FFFFFF';
    });

    const tds = el.querySelectorAll('td');
    tds.forEach((td) => {
      td.style.padding = '10px 12px';
      td.style.border = '1px solid #E2E8F0';
      td.style.color = '#1E293B';
    });

    // Blockquotes as clinical callout boxes
    const quotes = el.querySelectorAll('blockquote');
    quotes.forEach((q) => {
      q.style.borderLeft = '4px solid #0EA5E9';
      q.style.backgroundColor = '#F0F9FF';
      q.style.padding = '12px 16px';
      q.style.margin = '16px 0';
      q.style.borderRadius = '0 8px 8px 0';
      q.style.color = '#0369A1';
    });

    // Hide interactive buttons or action bars inside the clone
    const actions = el.querySelectorAll('button, .action-bar, .no-print');
    actions.forEach((btn) => btn.remove());
  };

  applyLightStyles(contentClone);
  printContainer.appendChild(contentClone);

  // Professional footer note
  const footerDiv = document.createElement('div');
  footerDiv.style.marginTop = '36px';
  footerDiv.style.paddingTop = '14px';
  footerDiv.style.borderTop = '1px solid #E2E8F0';
  footerDiv.style.fontSize = '11px';
  footerDiv.style.color = '#64748B';
  footerDiv.style.display = 'flex';
  footerDiv.style.justifyContent = 'space-between';
  footerDiv.innerHTML = `
    <span>IRIS AI Health Assistant · For informational purposes only</span>
    <span>Consult your physician for diagnosis and medical decisions</span>
  `;
  printContainer.appendChild(footerDiv);

  document.body.appendChild(printContainer);

  try {
    const canvas = await html2canvas(printContainer, {
      scale: 2, // Crisp Retina resolution
      backgroundColor: '#FFFFFF',
      useCORS: true,
      logging: false,
      windowWidth: 794
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfW = pdf.internal.pageSize.getWidth();
    const pdfH = (canvas.height * pdfW) / canvas.width;
    const pageH = pdf.internal.pageSize.getHeight();

    let yOffset = 0;
    while (yOffset < pdfH) {
      if (yOffset > 0) {
        pdf.addPage();
      }
      pdf.addImage(imgData, 'PNG', 0, -yOffset, pdfW, pdfH);
      yOffset += pageH;
    }

    const pdfFilename = `${safeTitle}_Iris.pdf`;

    // Use File System Access API to prompt the user for save location
    if (typeof window !== 'undefined' && 'showSaveFilePicker' in window) {
      try {
        const handle = await window.showSaveFilePicker({
          suggestedName: pdfFilename,
          types: [
            {
              description: 'PDF Document (*.pdf)',
              accept: { 'application/pdf': ['.pdf'] }
            }
          ]
        });
        const pdfBlob = pdf.output('blob');
        const writableStream = await handle.createWritable();
        await writableStream.write(pdfBlob);
        await writableStream.close();
      } catch (pickerErr) {
        // User cancelled the dialog — exit gracefully
        if (pickerErr.name === 'AbortError') {
          return;
        }
        // Fallback to standard browser download on any other error
        console.warn('[generatePDF] showSaveFilePicker failed, falling back:', pickerErr);
        pdf.save(pdfFilename);
      }
    } else {
      // Fallback for browsers that don't support showSaveFilePicker
      pdf.save(pdfFilename);
    }
  } catch (err) {
    console.error('[generatePDF] Failed to create PDF:', err);
    throw err;
  } finally {
    if (document.body.contains(printContainer)) {
      document.body.removeChild(printContainer);
    }
  }
}

export default generatePDF;
